version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db/test
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: